repos:
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: ['--ignore=E501,W504,W503,W605,C901']
-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
    - id: isort
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args:
          - --ignore=D105,D107,D200,D202,D203,D212
          - --match-dir='[^\tests].*'
          - --match='(?!__init__).*\.py'
