name: style

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 isort
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors, undefined names, obsolete whitespaces or unconventional statements
          flake8 . --select=E2,E7,E9,F63,F7,F82,F84 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --ignore=E501,W504,W503,W605,C901
      - name: Import check with isort
        run: |
          isort --check-only --diff .
